version: "3.3"
services:
  db:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306:3306
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=cars
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
  backend:
    build: backend
    restart: always
    secrets:
      - db-password
    volumes:
      - ./backend/config:/backend/config
      - ./backend/data:/backend/data
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backnet:
  frontnet:
